name: Terraform Deployment

on:
  push:
    branches: [ "master" ]

permissions:
  id-token: write
  contents: read
      
jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name : Checkout master
        uses: actions/checkout@master
            
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name : ${{ secrets.AWS_SESSION_NAME }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        run: terraform fmt
      
      - name: Terraform Init
        run: terraform init -backend-config="bucket=${{ secrets.S3_STATE_BUCKET }}" -backend-config="key=${{ secrets.S3_STATE_BUCKET_KEY }}" -backend-config="region=${{ secrets.REGION }}"

      - name: Terraform Validate
        run: terraform validate
      
      - name : Terraform Plan
        run : terraform plan -out=tfplan -var s3_bucket_name=${{ secrets.S3_STATIC_BUCKET_NAME }}

      - name: Terraform Apply
        run: terraform apply tfplan 
      

